package jogo.logica.estados;

public enum Situacao {
    MENU_SELECTION,
    MODE_SELECTION,
    REGISTAR_NOMES,
    VITORIA,
    ESPERA_JOGADA_ALEATORIA, MINI_JOGO, ESPERA_JOGADA_ESPECIAL, EMPATE, ESPERA_JOGADA_HUMANO
}
