package jogo.iu.grafico;

public interface Propriedades {
    String PROPRIEDADE_MODE_SELECTION = "PROPRIEDADE_MODE_SELECTION";
    String PROPRIEDADE_MENU_SELECTION = "PROPRIEDADE_MENU_SELECTION";
    String PROPRIEDADE_REGISTAR_NOMES = "PROPRIEDADE_REGISTAR_NOMES";
    String PROPRIEDADE_JOGAR = "PROPRIEDADE_JOGAR";
    String PROPRIEDADE_MINIJOGO = "PROPRIEDADE_MINIJOGO";
}
